/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutProfileRouteImport } from './routes/_layout/profile'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as LayoutFriendsIndexRouteImport } from './routes/_layout/friends/index'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout/chat/index'
import { Route as LayoutFriendsRequestsRouteImport } from './routes/_layout/friends/requests'
import { Route as LayoutChatUsernameRouteImport } from './routes/_layout/chat/$username'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LayoutProfileRoute = LayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/profile.lazy').then((d) => d.Route),
)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-up.lazy').then((d) => d.Route))
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/sign-in.lazy').then((d) => d.Route))
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/reset-password.lazy').then((d) => d.Route),
)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/forgot-password.lazy').then((d) => d.Route),
)
const LayoutFriendsIndexRoute = LayoutFriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/friends/index.lazy').then((d) => d.Route),
)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/chat/index.lazy').then((d) => d.Route),
)
const LayoutFriendsRequestsRoute = LayoutFriendsRequestsRouteImport.update({
  id: '/friends/requests',
  path: '/friends/requests',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/friends/requests.lazy').then((d) => d.Route),
)
const LayoutChatUsernameRoute = LayoutChatUsernameRouteImport.update({
  id: '/chat/$username',
  path: '/chat/$username',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/chat/$username.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/profile': typeof LayoutProfileRoute
  '/chat/$username': typeof LayoutChatUsernameRoute
  '/friends/requests': typeof LayoutFriendsRequestsRoute
  '/chat/': typeof LayoutChatIndexRoute
  '/friends/': typeof LayoutFriendsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/profile': typeof LayoutProfileRoute
  '/chat/$username': typeof LayoutChatUsernameRoute
  '/friends/requests': typeof LayoutFriendsRequestsRoute
  '/chat': typeof LayoutChatIndexRoute
  '/friends': typeof LayoutFriendsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_layout/profile': typeof LayoutProfileRoute
  '/_layout/chat/$username': typeof LayoutChatUsernameRoute
  '/_layout/friends/requests': typeof LayoutFriendsRequestsRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/friends/': typeof LayoutFriendsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/chat/$username'
    | '/friends/requests'
    | '/chat/'
    | '/friends/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/chat/$username'
    | '/friends/requests'
    | '/chat'
    | '/friends'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_layout'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_layout/profile'
    | '/_layout/chat/$username'
    | '/_layout/friends/requests'
    | '/_layout/chat/'
    | '/_layout/friends/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/friends/': {
      id: '/_layout/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof LayoutFriendsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/friends/requests': {
      id: '/_layout/friends/requests'
      path: '/friends/requests'
      fullPath: '/friends/requests'
      preLoaderRoute: typeof LayoutFriendsRequestsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/chat/$username': {
      id: '/_layout/chat/$username'
      path: '/chat/$username'
      fullPath: '/chat/$username'
      preLoaderRoute: typeof LayoutChatUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LayoutRouteChildren {
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutChatUsernameRoute: typeof LayoutChatUsernameRoute
  LayoutFriendsRequestsRoute: typeof LayoutFriendsRequestsRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
  LayoutFriendsIndexRoute: typeof LayoutFriendsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutChatUsernameRoute: LayoutChatUsernameRoute,
  LayoutFriendsRequestsRoute: LayoutFriendsRequestsRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
  LayoutFriendsIndexRoute: LayoutFriendsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
